apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: frases
  labels:
    app: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "backend"
    tags.datadoghq.com/version: "1.4.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "backend"
        tags.datadoghq.com/version: "1.4.0"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/python-lib.version: "latest"
        ad.datadoghq.com/backend.logs: '[{"source":"python","service":"backend"}]'
    spec:
      containers:
      - name: backend
        image: robarros/backend:v2
        ports:
        - containerPort: 8080
        env:
        - name: DD_SERVICE
          value: "backend"
        - name: DD_ENV
          value: "dev"
        - name: DD_VERSION
          value: "1.4.0"
        - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        # - name: DD_TRACE_SAMPLE_RATE
        #   value: "1"
        # - name: DD_PROFILING_ENABLED
        #   value: "true"
        # - name: DD_RUNTIME_METRICS_ENABLED
        #   value: "true"
        # - name: DD_AGENT_HOST
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: frases
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
