---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: frases
  labels:
    app: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "backend"
    tags.datadoghq.com/version: "1.21.0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "backend"
        tags.datadoghq.com/version: "1.21.0"
        sidecar.istio.io/inject: "true"
        admission.datadoghq.com/enabled: "true"
        # admission.datadoghq.com/config.mode: "socket"
      annotations:
        admission.datadoghq.com/python-lib.version: "latest"
        ad.datadoghq.com/backend.logs: '[{"source":"python","service":"backend"}]'
    spec:
      containers:
      - name: backend
        image: robarros/backend:v13
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION 
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
          value: "true"
        - name: DD_TAGS
          value: "env:dev,service:backend"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_STARTUP_LOGS
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_APM_IGNORE_RESOURCES
          value: "GET /healthz, GET /stats/prometheus"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: QUOTE_URL 
          value: "https://dummyjson.com/quotes/random"
        - name: VERSION
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.labels['tags.datadoghq.com/version']
  strategy:
    canary:
      # dynamicStableScale: true
      trafficRouting:
        istio:
          virtualService:
            name: backend-vs
            routes:
            - primary
          destinationRule:
            name: backend-destrule
            canarySubsetName: canary
            stableSubsetName: stable
      # steps:
      # - setWeight: 33
      # - pause: {}
      # - setWeight: 66
      # - pause: {}
      # - setWeight: 75
      # - pause: {}

---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  namespace: frases
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: backend-destrule
  namespace: frases
spec:
  host: svc-backend.frases.svc.cluster.local
  # trafficPolicy:
  #   loadBalancer:
  #     simple: ROUND_ROBIN
  #     warmup:
  #       minimumPercent: 10
  #       duration: 1m
  #       aggression: 1.0
  subsets:
  - name: stable
    labels:
      app: backend
  - name: canary
    labels:
      app: backend

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend-vs
  namespace: frases
spec:
  hosts:
  - svc-backend                      
  - svc-backend.frases                      
  - svc-backend.frases.svc.cluster.local
  gateways:
  - mesh
  http:
  - name: primary
    match:
    - uri:
        prefix: /
    timeout: 25s
    retries:
      attempts: 2
      perTryTimeout: 12s
      retryOn: "reset,connect-failure,retriable-4xx"
    fault:
      # abort:
      #   percentage:
      #     value: 50        
      #   httpStatus: 400 
      # delay:
      #   percentage:
      #     value: 50
      #   fixedDelay: 5s
    route:
    - destination:
        host: svc-backend.frases.svc.cluster.local
        subset: stable
        port:
          number: 8080
      weight: 100
    - destination:
        host: svc-backend.frases.svc.cluster.local
        subset: canary
        port:
          number: 8080
      weight: 0

---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: dummyjson-external
  namespace: frases
spec:
  hosts:
  - dummyjson.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: HTTP
  resolution: DNS

---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: dummyjson-vs
  namespace: frases
spec:
  gateways:
  - mesh
  hosts:
  - dummyjson.com
  http:
  - retries:
      attempts: 3
      perTryTimeout: 10s
    route:
    - destination:
        host: dummyjson.com
        port:
          number: 443
    timeout: 30s

---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: dummyjson-tls
  namespace: frases
spec:
  host: dummyjson.com
  trafficPolicy:
    tls:
      mode: SIMPLE
      sni: dummyjson.com


# ---
# apiVersion: networking.istio.io/v1beta1
# kind: DestinationRule
# metadata:
#   name: backend-destrule
#   namespace: frases
# spec:
#   host: svc-backend.frases.svc.cluster.local
#   trafficPolicy:
#     loadBalancer:
#       simple: ROUND_ROBIN
#     connectionPool:
#       tcp:
#         maxConnections: 100              # Máx 100 conexões TCP
#       http:
#         http1MaxPendingRequests: 100     # Máx 100 req pendentesky1.0
#         http1MaxRequests: 200            # Máx 200 req simultâneas
#         h2UpgradePolicy: UPGRADE         # Usar HTTP/2
#     outlierDetection:
#       consecutive5xxErrors: 5            # 5 erros = remove do pool
#       interval: 30s                      # Verificar a cada 30s
#       baseEjectionTime: 30s              # 30s mínimo removido
#       maxEjectionPercent: 50             # Não remover mais de 50% dos pods
#       minRequestVolume: 5                # Mínimo 5 req antes de detectar
#       splitExternalLocalOriginErrors: true # Considerar erros externos
#   subsets:
#   - name: stable
#     labels:
#       app: backend
#   - name: canary
#     labels:
#       app: backend



