apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-front
  namespace: frases
  labels:
    app: api-front
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "api-front"
    tags.datadoghq.com/version: "1.4.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-front
  template:
    metadata:
      labels:
        app: api-front
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "api-front"
        tags.datadoghq.com/version: "1.4.0"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/python-lib.version: "latest"
    spec:
      containers:
      - name: api-front
        image: robarros/service1:v1
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE2_URL
          value: "http://svc-backend:8080/frases"
        - name: DD_SERVICE
          value: "api-front"
        - name: DD_ENV
          value: "dev"
        - name: DD_VERSION
          value: "1.4.0"
        - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        # - name: DD_TRACE_SAMPLE_RATE
        #   value: "1"
        # - name: DD_PROFILING_ENABLED
        #   value: "true"
        # - name: DD_RUNTIME_METRICS_ENABLED
        #   value: "true"
        # - name: DD_AGENT_HOST
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-front
  namespace: frases
spec:
  type: ClusterIP
  selector:
    app: api-front
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frases-virtualti-net-cert
  namespace: frases
spec:
  secretName: frases-virtualti-net-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "frases.virtualti.net"
  dnsNames:
    - "frases.virtualti.net"
  privateKey:
    rotationPolicy: Never

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frases-ingress
  namespace: frases
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: frases.virtualti.net
    external-dns.alpha.kubernetes.io/target: 150.136.247.86
    # nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # nginx.ingress.kubernetes.io/auth-tls-secret: frases/ca-secret
    # nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - frases.virtualti.net
      secretName: frases-virtualti-net-tls
  rules:
    - host: frases.virtualti.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-api-front
                port:
                  number: 8080