---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api-front
  namespace: frases
  labels:
    app: api-front
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "api-front"
    tags.datadoghq.com/version: "1.21.0"
spec:
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-front
  template:
    metadata:
      labels:
        app: api-front
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "api-front"
        tags.datadoghq.com/version: "1.21.0"
        sidecar.istio.io/inject: "true"
      annotations:
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/python-lib.version: "latest"
        ad.datadoghq.com/api-front.logs: '[{"source":"python","service":"api-front"}]'
    spec:
      containers:
      - name: api-front
        image: robarros/api-front:v13
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: SERVICE2_URL
          value: "http://svc-backend:8080/frases"
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION 
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_DYNAMIC_INSTRUMENTATION_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_STARTUP_LOGS
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: DD_APM_IGNORE_RESOURCES
          value: "GET /healthz/ready, GET /stats/prometheus"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: VERSION
          valueFrom: 
            fieldRef: 
              fieldPath: metadata.labels['tags.datadoghq.com/version']
  strategy:
    canary:
      dynamicStableScale: true
      canaryService: svc-api-front-canary
      stableService: svc-api-front-stable
      trafficRouting:
        istio:
          virtualService:
            name: api-front-vs
            routes:
            - primary
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 75
      - pause: {}

---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-front-stable
  namespace: frases
  labels:
    app: api-front
spec:
  type: ClusterIP
  selector:
    app: api-front
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-front-canary
  namespace: frases
  labels:
    app: api-front
spec:
  type: ClusterIP
  selector:
    app: api-front
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frases-gateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: frases.virtualti.net
    external-dns.alpha.kubernetes.io/target: 129.153.11.167
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "frases.virtualti.net"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "frases.virtualti.net"
    tls:
      mode: SIMPLE
      credentialName: frases-virtualti-net-tls

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-front-vs
  namespace: frases
spec:
  hosts:
  - "frases.virtualti.net"
  gateways:
  - istio-system/frases-gateway
  http:
  - name: primary
    route:
    - destination:
        host: svc-api-front-stable.frases.svc.cluster.local
        port:
          number: 8080
      weight: 100
    - destination:
        host: svc-api-front-canary.frases.svc.cluster.local
        port:
          number: 8080
      weight: 0


